"""Normalize LLM markdown into clean, readable engineering docs."""

import re
from typing import Optional

DOC_TITLES = {
    "PROJECT_SPEC.md": "Project Specification",
    "TASKS.md": "Implementation Tasks",
    "ARCHITECTURE.md": "System Architecture",
    "DECISIONS.md": "Engineering Decisions",
    "RISKS.md": "Risks and Mitigations",
    "TEST_PLAN.md": "Test Plan",
    "DEBATE_SUMMARY.md": "Debate Summary",
}

FORMAT_RULES = """
STRICT MARKDOWN FORMAT (follow exactly):
- One H1 title at the top: # Title
- Use ## for section headings only (no ### unless necessary, max one level deep)
- Use simple hyphen bullets: - item text
- Do NOT wrap labels in **bold** on every line
- Do NOT use nested bullet trees deeper than 2 levels
- Plain English. Short paragraphs (2-3 sentences max per section intro)
- No JSON, no code fences, no raw asterisk mess like * **Foo:**
- No "Here is the document" preamble — start directly with # Title
"""


def clean_markdown(content: str, filename: Optional[str] = None) -> str:
    if not content or not content.strip():
        title = DOC_TITLES.get(filename or "", "Document")
        return f"# {title}\n\n_No content generated._\n"

    text = content.strip()

    # Strip code fences
    text = re.sub(r"^```(?:markdown|md|json)?\s*\n?", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\n```\s*$", "", text)

    # Unescape common JSON artifacts
    text = text.replace("\\n", "\n").replace('\\"', '"')

    # Normalize bullet markers
    text = re.sub(r"^[\*\+]\s+", "- ", text, flags=re.MULTILINE)
    text = re.sub(r"^(\s*)[\*\+]\s+", r"\1- ", text, flags=re.MULTILINE)

    # Convert "* **Section:**" or "- **Section:**" style to ## Section
    text = re.sub(
        r"^-\s+\*\*([^*]+):\*\*\s*$",
        r"## \1",
        text,
        flags=re.MULTILINE,
    )
    text = re.sub(
        r"^\*\s+\*\*([^*]+):\*\*\s*$",
        r"## \1",
        text,
        flags=re.MULTILINE,
    )

    # Lines that are only **Label** -> ## Label
    text = re.sub(r"^\*\*([^*]+)\*\*\s*$", r"## \1", text, flags=re.MULTILINE)

    # Soften inline **bold** in bullets: "- **text:** rest" -> "- rest" or keep simple
    def simplify_bullet_bold(line: str) -> str:
        if line.strip().startswith("- "):
            line = re.sub(r"\*\*([^*]+)\*\*:\s*", r"\1: ", line)
            line = re.sub(r"\*\*([^*]+)\*\*", r"\1", line)
        return line

    text = "\n".join(simplify_bullet_bold(ln) for ln in text.splitlines())

    # Remove excessive blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Fix broken bold (odd number of **)
    while text.count("**") % 2 != 0:
        text = text.replace("**", "", 1)

    # Ensure proper H1
    title = DOC_TITLES.get(filename or "", _title_from_filename(filename))
    if not re.match(r"^#\s+", text):
        text = f"# {title}\n\n{text}"
    else:
        # Replace first H1 with canonical title if it's ugly
        first_line = text.split("\n")[0]
        if filename and len(first_line) > 80 or ".md" in first_line.lower():
            text = re.sub(r"^#\s+.+", f"# {title}", text, count=1)

    # Remove duplicate consecutive headings
    lines = text.splitlines()
    cleaned_lines = []
    prev = ""
    for line in lines:
        if line.strip() == prev.strip() and line.startswith("#"):
            continue
        cleaned_lines.append(line)
        prev = line
    text = "\n".join(cleaned_lines)

    return text.strip() + "\n"


def _title_from_filename(filename: Optional[str]) -> str:
    if not filename:
        return "Document"
    return filename.replace(".md", "").replace("_", " ").title()


def wrap_with_template(filename: str, body: str) -> str:
    """Add a short footer for consistency."""
    title = DOC_TITLES.get(filename, _title_from_filename(filename))
    body = clean_markdown(body, filename)
    if "Generated by IHS Planner" not in body:
        body = body.rstrip() + "\n\n---\n*Generated by Intelligent Harness System*\n"
    return body
