"""Per-run project environment variables (stored server-side in run_state.json)."""
from __future__ import annotations

from pathlib import Path
from typing import Any

from harness.run_state import load_state, save_state


def mask_secret(value: str) -> str:
    if not value:
        return ""
    if len(value) <= 6:
        return "••••••"
    return f"{value[:3]}…{value[-2:]}"


def load_project_env(run_dir: Path) -> dict[str, str]:
    state = load_state(run_dir) or {}
    raw = state.get("project_env") or {}
    return {str(k): str(v) for k, v in raw.items() if v}


def save_project_env(run_dir: Path, env: dict[str, str], *, use_demo: bool = False) -> None:
    from harness.env_requirements import DEMO_ENV_VALUES

    state = load_state(run_dir) or {"run_id": run_dir.name}
    cleaned = {k.strip(): v.strip() for k, v in env.items() if k.strip() and v.strip()}
    if use_demo:
        for key, demo in DEMO_ENV_VALUES.items():
            if key not in cleaned and demo:
                cleaned.setdefault(key, demo)
    state["project_env"] = cleaned
    state["project_env_demo"] = bool(use_demo)
    save_state(run_dir, state)


def project_env_for_api(run_dir: Path) -> dict[str, Any]:
    env = load_project_env(run_dir)
    return {
        "values": {k: mask_secret(v) for k, v in env.items()},
        "has_values": {k: bool(v) for k, v in env.items()},
        "configured_count": len(env),
    }


def write_local_env_file(project_dir: Path, env: dict[str, str]) -> None:
    """Write .env.local for local npm build (gitignored)."""
    if not env:
        return
    lines = ["# Generated by Intelligent Harness — do not commit secrets\n"]
    for k, v in sorted(env.items()):
        safe = v.replace("\n", "")
        lines.append(f"{k}={safe}\n")
    (project_dir / ".env.local").write_text("".join(lines), encoding="utf-8")
