"""Extract file payloads from LLM responses (JSON, fenced blocks, path markers)."""
from __future__ import annotations

import json
import re
from typing import List


def extract_files_from_llm(raw: str) -> List[dict]:
    """Return list of {path, content} from various LLM output formats."""
    if not raw or not raw.strip():
        return []

    text = raw.strip()

    # Strip markdown code fences
    fence = re.search(r"```(?:json)?\s*([\s\S]*?)```", text, re.IGNORECASE)
    if fence:
        text = fence.group(1).strip()

    files: List[dict] = []

    # Standard JSON object
    for candidate in _json_candidates(text):
        parsed = files_from_json_obj(candidate)
        if parsed:
            return parsed

    # Multiple fenced file blocks: ```tsx file:app/page.tsx
    block_pat = re.compile(
        r"```(?:tsx?|jsx?|javascript|typescript|css)?\s*"
        r"(?:file:)?([^\n`]+)\n([\s\S]*?)```",
        re.IGNORECASE,
    )
    for m in block_pat.finditer(raw):
        path = m.group(1).strip().strip('"').strip("'")
        content = m.group(2).strip()
        if path and content and _looks_like_source(path, content):
            files.append({"path": _norm_path(path), "content": content})

    if files:
        return files

    # Path comment before fence: // app/page.tsx
    alt = re.compile(
        r"(?:^|\n)(?:#+\s*|//\s*|File:\s*)([a-zA-Z0-9_./-]+\.(?:tsx?|jsx?|css))\s*\n```[\w]*\n([\s\S]*?)```",
        re.MULTILINE,
    )
    for m in alt.finditer(raw):
        files.append({"path": _norm_path(m.group(1)), "content": m.group(2).strip()})

    return files


def files_from_json_obj(data: dict) -> List[dict]:
    out: List[dict] = []
    files = data.get("files")
    if isinstance(files, list):
        for f in files:
            if not isinstance(f, dict):
                continue
            path = f.get("path") or f.get("file") or ""
            content = f.get("content") or f.get("code") or ""
            if path and content:
                out.append({"path": _norm_path(str(path)), "content": str(content)})
    elif data.get("path") and data.get("content"):
        out.append({"path": _norm_path(str(data["path"])), "content": str(data["content"])})
    elif data.get("file") and data.get("content"):
        out.append({"path": _norm_path(str(data["file"])), "content": str(data["content"])})
    return out


def _json_candidates(text: str) -> List[dict]:
    results: List[dict] = []
    start = 0
    while True:
        i = text.find("{", start)
        if i < 0:
            break
        for end in range(len(text), i, -1):
            chunk = text[i:end]
            try:
                obj = json.loads(chunk)
                if isinstance(obj, dict):
                    results.append(obj)
                    break
            except json.JSONDecodeError:
                continue
        start = i + 1
    return results


def _norm_path(path: str) -> str:
    p = path.replace("\\", "/").lstrip("./")
    # LLM sometimes returns absolute or src/ paths
    if p.startswith("src/"):
        p = p[4:]
    return p


def _looks_like_source(path: str, content: str) -> bool:
    if not content or len(content) < 20:
        return False
    ext = path.rsplit(".", 1)[-1].lower()
    if ext in ("tsx", "jsx", "ts", "js"):
        return "export" in content or "function" in content or "const" in content
    if ext == "css":
        return "{" in content
    return True


def is_placeholder_page(content: str) -> bool:
    c = content.lower()
    return "intelligent harness demo" in c and "generated by the builder engine" in c
