"""Loads verified models from selected_models.json (generated by scripts/check_models.py)."""

import json
from pathlib import Path
from typing import Dict, Optional

from harness.providers.model_candidates import ALL_CANDIDATES

_REGISTRY_PATH = Path(__file__).parent / "selected_models.json"
_cached: Optional[Dict[str, str]] = None

# Hardcoded fallbacks if no verification run yet
FALLBACK_MODELS = {
    "groq": "llama-3.3-70b-versatile",
    "groq_fast": "llama-3.3-70b-versatile",
    "groq_planner": "openai/gpt-oss-120b",
    "openrouter": "openrouter/free",
    "openrouter_fast": "openrouter/free",
    "openrouter_planner": "openrouter/free",
    "openrouter_fallback": "openrouter/free",
    "openrouter_default": "openrouter/free",
    "gemini": "gemini-2.5-flash-lite",
    "gemini_planner": "gemini-2.5-flash-lite",
    "gemini_fast": "gemini-2.5-flash-lite",
}


def load_registry() -> Dict[str, str]:
    global _cached
    if _cached is not None:
        return _cached
    if _REGISTRY_PATH.exists():
        try:
            _cached = json.loads(_REGISTRY_PATH.read_text(encoding="utf-8"))
            return _cached
        except (json.JSONDecodeError, OSError):
            pass
    _cached = dict(FALLBACK_MODELS)
    return _cached


def _env_override(provider: str) -> str | None:
    import os

    env_map = {
        "groq": "GROQ_MODEL",
        "gemini": "GEMINI_MODEL",
        "openrouter": "OPENROUTER_MODEL",
    }
    val = os.getenv(env_map.get(provider, ""), "").strip()
    return val or None


def get_model(provider: str, role: str = "default") -> str:
    env = _env_override(provider)
    if env:
        return env
    reg = load_registry()
    keys = [
        f"{provider}_{role}",
        provider,
        f"{provider}_default",
    ]
    for key in keys:
        if key in reg and reg[key]:
            return reg[key]
    return FALLBACK_MODELS.get(f"{provider}_{role}") or FALLBACK_MODELS.get(provider, "")


def save_registry(data: Dict[str, str]) -> Path:
    global _cached
    _cached = data
    _REGISTRY_PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return _REGISTRY_PATH


def candidates_for(provider: str, role: str = "default") -> list:
    return ALL_CANDIDATES.get(provider, {}).get(role, ALL_CANDIDATES.get(provider, {}).get("default", []))
